CREATE TABLE TS05_01.PRODUCT_PRICE_HISTORY 
(PRODUCT_ID NUMBER(5), 
PRODUCT_NAME VARCHAR2(32), 
SUPPLIER_NAME VARCHAR2(32), 
UNIT_PRICE NUMBER(7,2) ); 


CREATE TABLE TS05_01.PRODUCT
(PRODUCT_ID NUMBER(5), 
PRODUCT_NAME VARCHAR2(32), 
SUPPLIER_NAME VARCHAR2(32), 
UNIT_PRICE NUMBER(7,2) ); 

CREATE OR REPLACE PROCEDURE TS05_01.CREATE_TRIGGER 
IS
BEGIN

CREATE OR REPLACE TRIGGER TS05_01.PRICE_HISTORY_TRIGGER 
BEFORE UPDATE OF UNIT_PRICE 
ON TS05_01.PRODUCT 
FOR EACH ROW 
BEGIN 
INSERT INTO TS05_01.PRODUCT_PRICE_HISTORY 
VALUES 
(:NEW.PRODUCT_ID, 
 :NEW.PRODUCT_NAME, 
 :NEW.SUPPLIER_NAME, 
 :NEW.UNIT_PRICE); 
END;

END;
/