CREATE TABLE TS02_01.actor (
  actor_id smallint(5) primary key,
  first_name varchar(45) NOT NULL,
	last_name varchar(45) NOT NULL,
  last_update timestamp NOT NULL 
  
  ) 
  
  CREATE TABLE TS03_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS04_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS05_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS06_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS07_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS08_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS09_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS10_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS11_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS12_01.country (
  Code char(3) NOT NULL DEFAULT '',
  Name char(52) NOT NULL DEFAULT '',
  Continent enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America') NOT NULL DEFAULT 'Asia',
  Region char(26) NOT NULL DEFAULT '',
  SurfaceArea float(10,2) NOT NULL DEFAULT '0.00',
  IndepYear smallint(6) DEFAULT NULL,
  Population int(11) NOT NULL DEFAULT '0',
  LifeExpectancy float(3,1) DEFAULT NULL,
  GNP float(10,2) DEFAULT NULL,
  GNPOld float(10,2) DEFAULT NULL,
  LocalName char(45) NOT NULL DEFAULT '',
  GovernmentForm char(45) NOT NULL DEFAULT '',
  HeadOfState char(60) DEFAULT NULL,
  Capital int(11) DEFAULT NULL,
  Code2 char(2) NOT NULL DEFAULT '',
  PRIMARY KEY (Code)
) 

CREATE TABLE TS12_02.countrylanguage (
  CountryCode char(3) NOT NULL DEFAULT '',
  Language char(30) NOT NULL DEFAULT '',
  IsOfficial enum('T','F') NOT NULL DEFAULT 'F',
  Percentage float(4,1) NOT NULL DEFAULT '0.0',
  PRIMARY KEY (CountryCode,Language),
  KEY CountryCode (CountryCode),
  CONSTRAINT countryLanguage_ibfk_1 FOREIGN KEY (CountryCode) REFERENCES country (Code)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE TS13_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS14_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS15_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS16_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS17_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS18_01.sample_superstore (
  id int(11) NOT NULL AUTO_INCREMENT,
  Row_ID int(11) DEFAULT NULL,
  Order_ID varchar(255) DEFAULT NULL,
  Order_Date date DEFAULT NULL,
  Ship_Date date DEFAULT NULL,
  Ship_Mode varchar(255) DEFAULT NULL,
  Customer_ID varchar(255) DEFAULT NULL,
  Customer_Name varchar(255) DEFAULT NULL,
  Segment varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Postal_Code int(11) DEFAULT NULL,
  Region varchar(255) DEFAULT NULL,
  Product_ID varchar(255) DEFAULT NULL,
  Category varchar(255) DEFAULT NULL,
  Sub_Category varchar(255) DEFAULT NULL,
  Product_Name varchar(255) DEFAULT NULL,
  Sales float DEFAULT NULL,
  Quantity int(11) DEFAULT NULL,
  Discount float DEFAULT NULL,
  Profit float DEFAULT NULL,
  PRIMARY KEY (id)
) 

CREATE TABLE TS19_01.user1 (
  user varchar(20) NOT NULL,
  age int(11) DEFAULT NULL,
  PRIMARY KEY (user)
) 

CREATE TABLE TS19_01.user2 (
  user varchar(20) NOT NULL,
  os varchar(20) DEFAULT NULL,
  PRIMARY KEY (user)
) 

CREATE TABLE TS20_01.orderdetails (
  ORDERNUMBER int(11) NOT NULL,
  PRODUCTCODE varchar(50) NOT NULL,
  QUANTITYORDERED int(11) NOT NULL,
  PRICEEACH decimal(17,0) NOT NULL,
  ORDERLINENUMBER smallint(6) NOT NULL,
  PRIMARY KEY (ORDERNUMBER,PRODUCTCODE)
) 

CREATE TABLE orders (
  ORDERNUMBER int(11) NOT NULL,
  ORDERDATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  REQUIREDDATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  SHIPPEDDATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  STATUS varchar(15) NOT NULL,
  COMMENTS varchar(30) DEFAULT NULL,
  CUSTOMERNUMBER int(11) NOT NULL,
  PRIMARY KEY (ORDERNUMBER)
)

CREATE TABLE products (
  PRODUCTCODE varchar(50) NOT NULL,
  PRODUCTNAME varchar(70) NOT NULL,
  PRODUCTLINE varchar(50) NOT NULL,
  PRODUCTSCALE varchar(10) NOT NULL,
  PRODUCTVENDOR varchar(50) NOT NULL,
  PRODUCTDESCRIPTION varchar(30) NOT NULL,
  QUANTITYINSTOCK smallint(6) NOT NULL,
  BUYPRICE decimal(17,0) NOT NULL,
  MSRP decimal(17,0) NOT NULL,
  PRIMARY KEY (PRODUCTCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8