CREATE  TABLE TS20_01.PARTY 
     (
      PARTYID INTEGER,
      PARTYNAME VARCHAR(20) 
      )
PRIMARY INDEX ( PARTYID );

CREATE PROCEDURE TS20_01.CUR_TAB()
BEGIN
DECLARE VAR1 INTEGER;
DECLARE VAR2 CHARACTER(30);
DECLARE C1  CURSOR FOR
SELECT PARTYID, PARTYNAME FROM TS20_01.PARTY ORDER BY PARTYID;
END;
