CREATE SET VOLATILE TABLE TS11_02.I_CUST03
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      DESIGNATION VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS11_02.INSERT_CASE_EMP6()
BEGIN

INSERT INTO TS11_02.I_CUST3 
SELECT CUST_ID,CUSTNAME,
CASE WHEN CUST_ID<4 THEN 'ASSOCIATE' 
WHEN CUST_ID>6 THEN 'MANAGER' 
ELSE 'LEAD' 
END DESIGNATION
 FROM TS11_02.I_CUST03;
 
 END;