CREATE SET VOLATILE TABLE TS11_01.M_EMPLOYEE6
     (
      EMPID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );

CREATE PROCEDURE TS11_01.CREATE_CASE_EMP5()
BEGIN

CREATE SET TABLE TS11_01.TEST1_7 AS 
(
SELECT EMPID,EMPNAME,CITY,SAL,
CASE WHEN EMPID<7 THEN 'ASSOCIATE' WHEN EMPID>8 THEN 'LEAD' ELSE 'MANAGER' END AS DESIGNATION 
FROM TS11_01.M_EMPLOYEE6 
);

END;