CREATE SET VOLATILE TABLE TS11_03.I_CUST018
    
     (
      CUST_ID INTEGER,
      DEPT_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      PHONEN1 INTEGER ,
      PHONEN2 INTEGER,
      PHONEN3 INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS11_03.INSERT_COALESCE_EMP8()
BEGIN

INSERT INTO TS11_03.I_CUST18
SELECT CUST_ID,CUSTNAME,
COALESCE(PHONEN1,PHONEN2,PHONEN3,'PHONE # NOT AVAILABLE') AS PHONENUM
FROM TS11_03.I_CUST018;

END;