CREATE SET VOLATILE TABLE TS04_01.I_CUST01    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS04_01.INSERT_TAB_CUST1()
BEGIN

INSERT INTO TS04_01.I_CUST1 
SELECT * 
FROM TS04_01.I_CUST01;

END ;