CREATE SET VOLATILE TABLE TS04_02.I_CUST02
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS04_02.INSERT_TAB_CUST2()
BEGIN

INSERT INTO TS04_02.I_CUST2(CUST_ID,CUSTNAME)
SELECT  CUST_ID,CUSTNAME 
FROM TS04_02.I_CUST02;

END;