CREATE SET VOLATILE  TABLE TS01_01.SRC_EMP
     (
      EMPID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS01_01.CREATE_TAB_EMP1()
BEGIN

CREATE  TABLE TS01_01.C_EMP 
AS(SELECT * FROM TS01_01.SRC_EMP);

END;