CREATE SET VOLATILE  TABLE TS01_02.SRC_EMP1
     (
      EMPID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS01_02.CREATE_TAB_EMP2()
BEGIN

CREATE TABLE TS01_02.C_EMP1 
AS(SELECT EMPID,EMPNAME,CITY,SAL FROM TS01_02.SRC_EMP1);

END;