CREATE TABLE TS20_01.SUPPLIERS6
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS20_01.ORDERS
(
ORDER_NUMBER NUMBER(10),
SUPPLIER_ID NUMBER(10),
CITY VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS20_01.Create_Tab_SUP_ORD_INNER
IS
BEGIN

CREATE TABLE TS20_01.SUP_ORD_INNER AS SELECT SUPPLIERS6.SUPPLIER_ID, SUPPLIERS6.SUPPLIER_NAME, ORDERS.ORDER_NUMBER  
FROM TS20_01.SUPPLIERS6   
INNER JOIN TS20_01.ORDERS
ON SUPPLIERS6.SUPPLIER_ID = ORDERS.SUPPLIER_ID;

END;
/
