
create procedure TS21.SP_PROD(
IN prodid  int, OUT  prodname varchar(20), OUT  pricep  int, OUT validityv  int)

BEGIN
select prod_name,price,validity into prodname,pricep,validityv  from TS21.TS21_SP_PRODUCT WHERE prod_id=prodid;
END;


CREATE SET TABLE TS21.TS21_sp_product ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      prod_id INTEGER,
      prod_name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      price INTEGER,
      validity INTEGER)
PRIMARY INDEX ( prod_id );


CREATE SET TABLE TS21.TS21_sp_product1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      prod_id INTEGER,
      prod_name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      price INTEGER,
      validity INTEGER)
PRIMARY INDEX ( prod_id );


CREATE SET TABLE TS01.TS01_salary ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmployeeNo INTEGER,
      Gross INTEGER,
      Deduction INTEGER,
      Netpay INTEGER,
      bonus INTEGER)
PRIMARY INDEX ( EmployeeNo );

CREATE SET TABLE TS01.TS01_salary1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmployeeNo INTEGER,
      Gross INTEGER,
      Deduction INTEGER)
PRIMARY INDEX ( EmployeeNo );

CREATE SET TABLE TS02.TS02_stud_sql ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      stu_id INTEGER,
      stu_name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      std INTEGER)
PRIMARY INDEX ( stu_id );

CREATE SET TABLE TS02.TS02_stud_src ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      stu_id INTEGER,
      stu_name VARCHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      std INTEGER)
PRIMARY INDEX ( stu_id );

CREATE SET TABLE TS03.TS03_details ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER,
      salary INTEGER,
      workexperience INTEGER)
PRIMARY INDEX ( sno );

CREATE SET TABLE TS04.TS04_marks ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      name VARCHAR(12) CHARACTER SET LATIN NOT CASESPECIFIC,
      std INTEGER,
      marks INTEGER)
PRIMARY INDEX ( name );

CREATE SET TABLE TS04.TS04_marks1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      name VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      std INTEGER,
      marks INTEGER)
PRIMARY INDEX ( name );

CREATE SET TABLE TS05.TS05_emp ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      empno INTEGER,
      empname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      salary INTEGER,
      yrsofexp INTEGER,
      deptname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( empno );

CREATE SET TABLE TS05.TS05_emp1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      empno INTEGER,
      empname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      salary INTEGER,
      yrsofexp INTEGER,
      annsal INTEGER)
PRIMARY INDEX ( empno );

CREATE SET TABLE TS06.TS06_employee ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmpName VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmpNo INTEGER,
      Deptno INTEGER,
      bonus INTEGER,
      deptname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( EmpName );

CREATE SET TABLE TS06.TS06_tgt_dept10 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      empname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      empno INTEGER,
      deptno INTEGER,
      bonus INTEGER,
      tot_sal INTEGER)
PRIMARY INDEX ( empname );



CREATE SET TABLE TS06.TS06_tgt_dept20 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      empname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      empno INTEGER,
      deptno INTEGER,
      bonus INTEGER,
      tot_sal INTEGER)
PRIMARY INDEX ( empname );



CREATE SET TABLE TS06.TS06_tgt_dept30 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      empname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      empno INTEGER,
      deptno INTEGER,
      bonus INTEGER,
      tot_sal INTEGER)
PRIMARY INDEX ( empname );



CREATE SET TABLE TS06.TS06_tgt_employeedef ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      empname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      empno INTEGER,
      deptno INTEGER,
      bonus INTEGER,
      tot_sal INTEGER)
PRIMARY INDEX ( empname );



CREATE SET TABLE TS07.TS07_details ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER,
      salary INTEGER,
      workexperience INTEGER)
PRIMARY INDEX ( sno );


CREATE SET TABLE TS07.TS07_details1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER,
      salary INTEGER,
      workexperience INTEGER,
      newsal INTEGER)
PRIMARY INDEX ( sno );


CREATE SET TABLE TS08.TS08_test ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER)
PRIMARY INDEX ( sno );

CREATE SET TABLE TS08.TS08_test1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER)
PRIMARY INDEX ( sno );

CREATE SET TABLE TS09.TS09_employee ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmpName VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmpNo INTEGER,
      Deptno INTEGER,
      bonus INTEGER,
      deptname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( EmpName );

CREATE SET TABLE TS10.TS10_employee ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmpName VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmpNo INTEGER,
      Deptno INTEGER,
      bonus INTEGER,
      deptname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( EmpName );


CREATE SET TABLE TS10.TS10_employee_lkup ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmpName VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmpNo INTEGER,
      Deptno INTEGER,
      bonus INTEGER,
      deptname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( EmpName );

CREATE SET TABLE TS11.TS11_Xml_Infbooks ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      titles VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      author VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      years INTEGER,
      price INTEGER)
PRIMARY INDEX ( titles );

CREATE SET TABLE TS12.TS12_employee ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      EmpName VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      EmpNo INTEGER,
      Deptno INTEGER,
      bonus INTEGER,
      deptname VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( EmpName );


CREATE SET TABLE TS17.TS17_phone1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      mobno INTEGER,
      sno INTEGER)
PRIMARY INDEX ( name );



CREATE SET TABLE TS17.TS17_phone1_tgt ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      mobno INTEGER,
      sno INTEGER)
PRIMARY INDEX ( name );



CREATE SET TABLE TS17.TS17_phone2 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      mobno INTEGER,
      sno INTEGER)
PRIMARY INDEX ( name );



CREATE SET TABLE TS19.TS19_test ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER)
PRIMARY INDEX ( sno );



CREATE SET TABLE TS19.TS19_test1 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      sno INTEGER,
      name VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      deptno INTEGER)
PRIMARY INDEX ( sno );



CREATE SET TABLE TS20.TS20_books ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      book VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      Titles VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      author VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      years INTEGER,
      price INTEGER)
PRIMARY INDEX ( book );
