CREATE TABLE TS22_01.SUPPLIERS8
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS22_01.ORDERS3
(
ORDER_NUMBER NUMBER(10),
SUPPLIER_ID NUMBER(10),
CITY VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS22_01.Create_Tab_SUP_ORD_RIGHT 
IS
BEGIN

CREATE TABLE TS22_01.SUP_ORD_RIGHT AS SELECT ORDERS3.ORDER_NUMBER, ORDERS3.CITY, SUPPLIERS8.SUPPLIER_NAME  
FROM TS22_01.SUPPLIERS8  
RIGHT OUTER JOIN TS22_01.ORDERS3  
ON SUPPLIERS8.SUPPLIER_ID = ORDERS3.SUPPLIER_ID;

END;
/