
CREATE SET VOLATILE TABLE TS03_01.EMPL2
    
     (
      EMP_ID INTEGER,
      DEPT_ID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMP_ID )
ON COMMIT PRESERVE ROWS;

CREATE MACRO TS03_01.EMPLOYEES
AS (SELECT EMP_ID,DEPT_ID,EMPNAME,CITY,SAL
 FROM TS03_01.EMPL2
WHERE EMP_ID=DEPT_ID 
 ORDER BY SAL DESC;);