CREATE SET VOLATILE TABLE TS09_05.M_CUST5
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID );

CREATE SET VOLATILE TABLE TS09_05.M_EMP5
     (
      EMPID INTEGER,
      FIRSTNAME VARCHAR(30) ,
      CITY VARCHAR(30) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );

CREATE PROCEDURE TS09_05.CREATE_CJOIN_EMP5()
BEGIN

CREATE SET TABLE TS09_05.T5 
AS(SELECT M_CUST5.CUST_ID,M_CUST5.CUSTNAME,M_EMP5.EMPID,M_EMP5.FIRSTNAME 
FROM TS09_05.M_CUST5 
CROSS  JOIN TS09_05.M_EMP5 
WHERE M_CUST5.CUST_ID=M_EMP5.EMPID);

END;