CREATE SET VOLATILE TABLE TS09_02.M_CUST2
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE SET VOLATILE TABLE TS09_02.M_EMP2
     (
      EMPID INTEGER,
      FIRSTNAME VARCHAR(30) ,
      CITY VARCHAR(30) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS09_02.CREATE_LOJOIN_EMP1()
BEGIN

CREATE  SET TABLE TS09_02.T2 
AS (SELECT M_CUST2.CUST_ID,M_CUST2.CUSTNAME,M_EMP2.EMPID,M_EMP2.FIRSTNAME 
FROM TS09_02.M_CUST2 
LEFT OUTER JOIN TS09_02.M_EMP2 
ON M_CUST2.CUST_ID=M_EMP2.EMPID);

END;