CREATE SET VOLATILE TABLE TS09_01.M_CUST1
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID );

CREATE SET VOLATILE TABLE TS09_01.M_EMP1
     (
      EMPID INTEGER,
      FIRSTNAME VARCHAR(30) ,
      CITY VARCHAR(30) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );

CREATE PROCEDURE TS09_01.CREATE_INJOIN_EMP()
BEGIN

CREATE SET TABLE TS09_01.T1 
AS(SELECT M_CUST1.CUST_ID,M_CUST1.CUSTNAME,M_EMP1.EMPID,M_EMP1.FIRSTNAME 
FROM TS09_01.M_CUST1 
INNER JOIN TS09_01.M_EMP1 
ON M_CUST1.CUST_ID=M_EMP1.EMPID);

END;