CREATE SET VOLATILE TABLE TS09_07.I_CUST05
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE SET VOLATILE TABLE TS09_07.I_CUST005
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS09_07.INSERT_ROJOIN_CUST2()
BEGIN

INSERT INTO TS09_07.I_CUST5  
SELECT  I_CUST05.CUST_ID,I_CUST05.CUSTNAME,I_CUST005.CUST_ID,I_CUST005.CUSTNAME 
FROM TS09_07.I_CUST05
RIGHT OUTER JOIN TS09_07.I_CUST005 
ON I_CUST05.CUST_ID=I_CUST005.CUST_ID;

END;