CREATE SET VOLATILE TABLE TS09_06.I_CUST04
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE SET VOLATILE TABLE TS09_06.I_CUST004
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS09_06.INSERT_LOJOIN_CUST1()
BEGIN

INSERT INTO TS09_06.I_CUST4  
SELECT  I_CUST04.CUST_ID,I_CUST04.CUSTNAME,I_CUST004.CUST_ID,I_CUST004.CUSTNAME 
FROM TS09_06.I_CUST04 
LEFT OUTER JOIN TS09_06.I_CUST004 
ON I_CUST04.CUST_ID=I_CUST004.CUST_ID;

END;