CREATE SET VOLATILE TABLE TS09_04.M_CUST4
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID );

CREATE SET VOLATILE TABLE TS09_04.M_EMP4
     (
      EMPID INTEGER,
      FIRSTNAME VARCHAR(30) ,
      CITY VARCHAR(30) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );

CREATE PROCEDURE TS09_04.CREATE_FOJOIN_EMP4()
BEGIN 

CREATE SET TABLE TS09_04.T4 
AS(SELECT M_CUST4.CUST_ID,M_CUST4.CUSTNAME,M_EMP4.EMPID,M_EMP4.FIRSTNAME 
FROM TS09_04.M_CUST4 
FULL OUTER JOIN TS09_04.M_EMP4 
ON M_CUST4.CUST_ID=M_EMP4.EMPID);

END;