CREATE SET VOLATILE TABLE TS12_01.L_EMP01
(
EMPID INTEGER,
EMPNAME VARCHAR(30),
CITY VARCHAR(30),
DEPT_ID INTEGER,
SAL INTEGER)
PRIMARY INDEX(EMPID)
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS12_01.INSERT_NULL_EMP9()
BEGIN

INSERT INTO TS12_01.L_EMP
SELECT EMPID,EMPNAME,CITY,DEPT_ID,SAL 
FROM TS12_01.L_EMP01
WHERE DEPT_ID IS NOT NULL AND DEPT_ID<=EMPID OR SAL>=DEPT_ID;

END;