CREATE TABLE TS04_01.DEPARTMENTS5 (
    DEPARTMENT_ID     NUMBER(10) NOT NULL,
    DEPARTMENT_NAME   VARCHAR2(50) NOT NULL
);

CREATE OR REPLACE PROCEDURE TS04_01.Trunc_Dep 
IS
BEGIN

TRUNCATE TABLE TS04_01.DEPARTMENTS5;

END;
/