CREATE TABLE TS18_01.TBL_EMP
(
ID INTEGER GENERATED ALWAYS AS IDENTITY
(
START WITH 1
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NO CYCLE ),
NAME VARCHAR(20),
PHONE VARCHAR(10));


CREATE PROCEDURE TS18_01.CREATE_IDENT_EMP15()
BEGIN

CREATE TABLE TS18_01.IDE_EMP
AS(SELECT ID,NAME 
FROM TS18_01.TBL_EMP 
WHERE ID=10)
WITH DATA PRIMARY INDEX(ID);

END;