CREATE  TABLE TS19_01.TAB_EMPLOYEE
( EMPLOYEEID INTEGER,
EMPLOYEENAME CHAR(30),
SALARY INTEGER);

CREATE TABLE TS19_01.TAB_EMPLOYEE_LOG
(
EMPLOYEEID INTEGER,
EMPLOYEENAME CHAR(30),
SALARY INTEGER,
USERID CHAR(30) DEFAULT USER,
LOADDT DATE DEFAULT DATE,
LOADTM  INTEGER DEFAULT TIME);

CREATE TRIGGER TS19_01.EMPLOYEETRI
AFTER INSERT ON TS19_01.TAB_EMPLOYEE
REFERENCING NEW_TABLE AS TS19_01.EMPLOYEENEW
FOR EACH STATEMENT
( INSERT INTO TS19_01.TAB_EMPLOYEE_LOG(EMPLOYEEID,EMPLOYEENAME,SALARY) 
SELECT EMPLOYEEID,EMPLOYEENAME,SALARY FROM TS19_01.EMPLOYEENEW;);