CREATE SET VOLATILE TABLE TS10_03.I_CUST011
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS10_03.INSERT_MAX_CUST7()
BEGIN

INSERT INTO TS10_03.I_CUST11
SELECT CUST_ID,CUSTNAME,CITY, 
 MAX(PRICE) as maxprice
FROM TS10_03.I_CUST011 
GROUP BY CUST_ID;

END;