CREATE SET VOLATILE TABLE TS10_04.I_CUST012
    
     (
      CUST_ID INTEGER,
      DEPT_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS10_04.INSERT_COUNT_CUST8()
BEGIN

INSERT INTO TS10_04.I_CUST12
SELECT COUNT(CUST_ID)as c_custid,DEPT_ID 
FROM TS10_04.I_CUST012
GROUP BY DEPT_ID;

END; 
