CREATE SET VOLATILE TABLE TS10_05.I_CUST013
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS10_05.INSERT_SUM_CUST9()
BEGIN

INSERT INTO TS10_05.I_CUST13
SELECT CUST_ID,CUSTNAME,CITY, 
 SUM(PRICE) as sumprice
FROM TS10_05.I_CUST013 
GROUP BY CUST_ID;

END;