CREATE SET VOLATILE TABLE TS10_02.I_CUST010
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS10_02.INSERT_MIN_CUST6()
BEGIN

INSERT INTO TS10_02.I_CUST10
SELECT CUST_ID,CUSTNAME,CITY,  
MIN(PRICE) as minprice 
FROM TS10_02.I_CUST010 
GROUP BY CUST_ID;

END;