CREATE SET VOLATILE TABLE TS10_01.I_CUST09
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS10_01.INSERT_AVG_CUST5()
BEGIN

INSERT INTO TS10_01.I_CUST9 
SELECT CUST_ID,CUSTNAME,CITY,  
AVG(PRICE) as avgprice
FROM TS10_01.I_CUST09 
GROUP BY CUST_ID;

END;