CREATE SET VOLATILE TABLE TS17_01.I_EMP019
    
     (
      EMP_ID INTEGER,
      DEPT_ID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMP_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS17_01.INSERT_RANK_EMP13()
BEGIN

INSERT INTO TS17_01.I_EMP19
SELECT EMP_ID,EMPNAME,SAL,
RANK() OVER(ORDER BY SAL DESC) AS "RANK" 
FROM TS17_01.I_EMP019;

END;