
CREATE SET VOLATILE TABLE TS17_02.I_EMP020
    
     (
      EMP_ID INTEGER,
      DEPT_ID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMP_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS17_02.INSERT_PART_EMP14()
BEGIN

INSERT INTO TS17_02.I_EMP20
SELECT EMPNAME,SAL ,
RANK() OVER(PARTITION BY EMPNAME 
ORDER BY SAL) AS NEWOUT
FROM TS17_02.I_EMP020;

END;
