CREATE SET VOLATILE TABLE TS08_04.I_CUST7
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE SET VOLATILE TABLE TS08_04.I_EMP7
    
     (
      EMP_ID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( EMP_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS08_04.INSERT_UNIONALL_CUST1()
BEGIN

INSERT INTO TS08_04.I_CUSTEMP7 
SELECT TS08_04.I_CUST7.CUST_ID,TS08_04.I_CUST7.CUSTNAME
 FROM TS08_04.I_CUST7
UNION ALL
SELECT TS08_04.I_EMP7.EMP_ID,TS08_04.I_EMP7.EMPNAME 
FROM TS08_04.I_EMP7;

END;