CREATE SET VOLATILE TABLE TS08_03.I_CUST6
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID )
ON COMMIT PRESERVE ROWS;

CREATE SET VOLATILE TABLE TS08_03.I_EMP6
    
     (
      EMP_ID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      PRICE INTEGER)
PRIMARY INDEX ( EMP_ID )
ON COMMIT PRESERVE ROWS;

CREATE PROCEDURE TS08_03.INSERT_UNION_CUST()
BEGIN

INSERT INTO TS08_03.I_CUSTEMP6 
SELECT TS08_03.I_CUST6.CUST_ID,TS08_03.I_CUST6.CUSTNAME 
FROM TS08_03.I_CUST6 
UNION 
SELECT TS08_03.I_EMP6.EMP_ID,TS08_03.I_EMP6.EMPNAME 
FROM TS08_03.I_EMP6;

END;