CREATE SET VOLATILE TABLE TS08_02.M_EMPLOYEE1
     (
      EMPID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );

CREATE SET VOLATILE TABLE TS08_02.M_CUSTOMER1
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(30) ,
      CITY VARCHAR(30) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID );

CREATE PROCEDURE TS08_02.CREATE_UNIONALL_EMP()
BEGIN

CREATE SET TABLE TS08_02.TEST1_2 AS(SELECT EMPID,EMPNAME,CITY,SAL  FROM TS08_02.M_EMPLOYEE1
UNION ALL 
SELECT CUST_ID,CUSTNAME,CITY,PRICE FROM TS08_02.M_CUSTOMER1);

END;