CREATE MULTISET TABLE TS08_01.M_EMPLOYEE
     (
      EMPID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );

CREATE MULTISET TABLE TS08_01.M_CUSTOMERS
    
     (
      CUST_ID INTEGER,
      CUSTNAME VARCHAR(30) ,
      CITY VARCHAR(30) ,
      PRICE INTEGER)
PRIMARY INDEX ( CUST_ID );

CREATE PROCEDURE TS08_01.CREATE_UNION_EMP()
BEGIN

CREATE SET TABLE TS08_01.TEST1_1 AS (SELECT EMPID,EMPNAME,CITY,SAL FROM TS08_01.M_EMPLOYEE 
UNION 
SELECT CUST_ID,CUSTNAME,CITY,PRICE FROM TS08_01.M_CUSTOMERS);

END;