CREATE TABLE TS17_01.SUPPLIERS2
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS17_01.SUPPLIERS3
(
SUPPLIER_ID1 NUMBER(10),
SUPPLIER_NAME1 VARCHAR2(20),
SUPPLIER_ADDRESS1 VARCHAR2(20)
);

CREATE TABLE TS17_01.COURSES_TBL1 (
    COURSE_NUMBER   NUMBER(10),
    COURSE_NAME     VARCHAR2(20)
);

CREATE OR REPLACE PACKAGE TS17_01.PKG1
IS
PROCEDURE INSERT_SUPP;
FUNCTION FINDCOURSE
(NAME_IN IN VARCHAR2)
RETURN NUMBER;
END;
/
--
CREATE OR REPLACE PACKAGE BODY TS17_01.PKG1
IS
PROCEDURE INSERT_SUPP
IS    
BEGIN    
INSERT INTO TS17_01.SUPPLIERS2 (SUPPLIER_ID,SUPPLIER_NAME,SUPPLIER_ADDRESS) 
SELECT S1.SUPPLIER_ID1, S1.SUPPLIER_NAME1, S1.SUPPLIER_ADDRESS1 FROM TS17_01.SUPPLIERS3 S1;    
END;
--
FUNCTION FINDCOURSE(NAME_IN IN VARCHAR2) 
RETURN NUMBER
IS
CNUMBER NUMBER;
CURSOR C1 IS
SELECT CT.COURSE_NUMBER
FROM TS17_01.COURSES_TBL1 CT
WHERE CT.COURSE_NAME = NAME_IN;
BEGIN	
OPEN C1;
FETCH C1 INTO CNUMBER;
IF C1%NOTFOUND THEN
CNUMBER := 9999;
END IF;
CLOSE C1;
RETURN CNUMBER;
EXCEPTION
WHEN OTHERS THEN
RAISE_APPLICATION_ERROR(-20001,'AN ERROR WAS ENCOUNTERED - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
END;
/