CREATE SET VOLATILE TABLE TS02_01.EMPL
    
     (
      EMP_ID INTEGER,
      DEPT_ID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMP_ID )
ON COMMIT PRESERVE ROWS;

CREATE VIEW TS02_01.EMPLOYEE 
AS SELECT EMP_ID,DEPT_ID,EMPNAME,CITY,SAL 
FROM TS02_01.EMPL;
