CREATE   TABLE TS16_01.SRC_EMP2
     (
      EMPID INTEGER,
      EMPNAME VARCHAR(50) ,
      CITY VARCHAR(50) ,
      SAL INTEGER)
PRIMARY INDEX ( EMPID );


CREATE JOIN INDEX  TS16_01.J_TEST
AS SELECT EMPID,EMPNAME,SAL 
 FROM TS16_01.SRC_EMP2
 PRIMARY INDEX(SAL);  
