CREATE TABLE TS21_01.SUPPLIERS7
(
SUPPLIER_ID NUMBER(10),
SUPPLIER_NAME VARCHAR2(20),
SUPPLIER_ADDRESS VARCHAR2(20)
);

CREATE TABLE TS21_01.ORDERS2
(
ORDER_NUMBER NUMBER(10),
SUPPLIER_ID NUMBER(10),
CITY VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE TS21_01.CREATE_TAB_SUP_ORD_LEFT 
IS
BEGIN

CREATE TABLE TS21_01.SUP_ORD_LEFT AS SELECT SUPPLIERS7.SUPPLIER_ID, SUPPLIERS7.SUPPLIER_NAME, ORDERS2.ORDER_NUMBER  
FROM TS21_01.SUPPLIERS7  
LEFT OUTER JOIN TS21_01.ORDERS2  
ON SUPPLIERS7.SUPPLIER_ID = ORDERS2.SUPPLIER_ID;

END;
/